
Platform	Syntax
CommunityBridge	community_bridge: PROJECT-NAME
GitHub Sponsors	github: USERNAME or github: [USERNAME, USERNAME, USERNAME, USERNAME]
IssueHunt	issuehunt: USERNAME
Ko-fi	ko_fi: USERNAME
Liberapay	liberapay: USERNAME
Open Collective	open_collective: USERNAME
Otechie	otechie: USERNAME
Patreon	patreon: USERNAME
Tidelift	tidelift: PLATFORM-NAME/PACKAGE-NAME
Custom URL	custom: LINK1 or custom: [LINK1, LINK2, LINK3, LINK4]
For Tidelift, use the platform-name/package-name syntax with the following github: [octocat, surftocat]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
