language: elixir
elixir: 1.0.5
services:
  - redis-server
otp_release:
  - 17.5
  - 18.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
  - cd installer && mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
