language: elixir
elixir:
  - 1.0.3
otp_release:
  - 17.1
matrix:
  include:
    - elixir: 1.0.4
      otp_release: 17.5
services:
  - redis-server
sudo: false
script:
  - mix test
  - cd installer && mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
