language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.1
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4
      env:
       - COWBOY_VERSION=1.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
  matrix:
    - COWBOY_VERSION=1.0
    - COWBOY_VERSION=2.0
before_script:
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
script:
  - mix test
  - cd installer && elixir -e "Version.match?(System.version, ~s(~> 1.5)) || System.halt(0)" -S mix test
  - cd ../ && npm install && npm test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
