name: CI
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.12.0
      env:
        ELIXIR_ASSERT_TIMEOUT: 2000

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.10.4
            otp: 23.1.1
          - elixir: 1.11.0
            otp: 21.3.8.18
          - elixir: 1.11.0
            otp: 23.1.1
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          apk add --no-progress --update git
          mix deps.get
      - run: mix test
      # - run: MIX_ENV=docs mix inch.report

  integration-test-elixir:
    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.12.0
      env:
        ELIXIR_ASSERT_TIMEOUT: 2000
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: some!Password
        ports:
          - 1433:1433
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.1
            otp: 21.3.8.18
          - elixir: 1.11.1
            otp: 23.1.1
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          apk add --no-progress --update git socat
      - name: Set up local proxies
        run: |
          socat TCP-LISTEN:5432,fork TCP-CONNECT:postgres:5432&
          socat TCP-LISTEN:3306,fork TCP-CONNECT:mysql:3306&
          socat TCP-LISTEN:1433,fork TCP-CONNECT:mssql:1433&
      - name: Run installer tests
        run: mix test
        working-directory: installer
      - name: Install dependencies
        run: mix deps.get
        working-directory: integration_test
      - name: Run integration tests
        run: mix test --include database
        working-directory: integration_test

  npm_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: 23.0.3
          elixir-version: 1.10.4
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.16
      - name: npm install and test
        run: |
          cd assets
          npm install
          npm test
